context:
  version: "9.3.2"

package:
  name: cspell
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cspell/-/cspell-${{ version }}.tgz
  sha256: c0d9d9e91a7cd4e8636b2e4a58b7f55f48743a7d530a7e257b7926facde6dddd

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cspell --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A Spell Checker for Code!
  homepage: https://cspell.org/
  repository: https://github.com/streetsidesoftware/cspell

extra:
  recipe-maintainers:
    - danielnachun
