context:
  version: "10.3.5"

package:
  name: cspell
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cspell/-/cspell-${{ version }}.tgz
  sha256: 28cbc1c57ca714c8014721b7dc09e1e983f1bcf024335109c99811ba90d15926

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cspell --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A Spell Checker for Code!
  homepage: https://cspell.org/
  repository: https://github.com/streetsidesoftware/cspell

extra:
  recipe-maintainers:
    - danielnachun
