context:
  version: "9.4.0"

package:
  name: cspell
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cspell/-/cspell-${{ version }}.tgz
  sha256: 72a026eaab0f22f214370c24c3dfbe4962ae6eb78e493e8975a41fabff530b1e

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cspell --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A Spell Checker for Code!
  homepage: https://cspell.org/
  repository: https://github.com/streetsidesoftware/cspell

extra:
  recipe-maintainers:
    - danielnachun
