context:
  version: "9.7.0"

package:
  name: cspell
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cspell/-/cspell-${{ version }}.tgz
  sha256: 34fca3034e19ac71def9c8596b17ee8583172bedecc2646cc81ced31e5c952de

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cspell --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A Spell Checker for Code!
  homepage: https://cspell.org/
  repository: https://github.com/streetsidesoftware/cspell

extra:
  recipe-maintainers:
    - danielnachun
