context:
  version: "10.3.1"

package:
  name: cspell
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cspell/-/cspell-${{ version }}.tgz
  sha256: 36983fd2c2c55df6465c451dc239b51a755a209d97d26f339b55d024ce792692

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - cspell --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A Spell Checker for Code!
  homepage: https://cspell.org/
  repository: https://github.com/streetsidesoftware/cspell

extra:
  recipe-maintainers:
    - danielnachun
